### ISSUE TITLE
Timestamp docs not updates on doc

### ISSUE THREAD

**Issue by agroernesto** [ethereum-attestation-service/eas-sdk#100]
I notice that the documentation on the readme regarding timestamps is not updated.

sending a PR to fix this

**Comment by agroernesto** [comment]
#101

**Comment by lbeder** [comment]
Hey @agroernesto,
You can use EAS to timestamp any data. Not only attestations.

**Comment by agroernesto** [comment]
Got it, but is not clear in the docs, may add the two examples.
Because if you try to use the example of the uid with the method on the readme will fail.
At least for me, I was doing some tinkering with the sdk and got stucked with that for a while.

Just trying to help 
Best

**Comment by lbeder** [comment]
Yeah, adding the UID examples, in addition to the existing generic example, is a good idea. If you could update your PR, I'd be more than happy merging it

**Comment by ernestosperanza** [comment]
Glad to do it, let me know if is ok, this way
 #102
