### ISSUE TITLE
Built-in IPFS support?

### ISSUE THREAD

**Issue by ccamrobertson** [ethereum-attestation-service/eas-sdk#30]
I see on EASScan that offchain attestations are added to IPFS (and pinned presumably). Are there plans to add IPFS support in `eas-sdk` via an external provider, or is this out of scope? 

If out of scope, an example publishing to IPFS (e.g. via a local node) might be nice to ensure the data is formatted correctly and the resulting CID is as expected.

**Comment by slavik0329** [comment]
@ccamrobertson,
Regarding your question about adding IPFS support in eas-sdk via an external provider, I'd like to clarify what you mean by "external provider." If you're referring to using a different IPFS service or hosting your own IPFS node, you can certainly do that.

To display offchain attestations, you can publish a text IPFS object with the same format as the offchain attestations on EASScan. For example, you can display those attestations like this: `https://easscan.org/offchain/ipfs/QmUmyGEzAyFx5eGCGfQ3usRZuyKsGmCKoFh2GAKGLnSZ7u`.

We'll be adding documentation on how offchain attestations should be formatted for IPFS, whether it's self-hosted or pinned on EASScan. The raw data format for offchain attestations on EASScan is the same as what's stored on IPFS, which looks like this:

```typescript
export interface AttestationShareablePackageObject {
  /** Signed typed data with attestation object (from the SDK) */
  sig: SignedOffchainAttestation;
  /** Address of the signer */
  signer: string;
} 
```

Additionally, the SDK has methods for encoding/decoding a Qm style IPFS hash from/to bytes32 for schema fields, such as [encodeQmHash](https://github.com/ethereum-attestation-service/eas-sdk/blob/bab671a5c53b2690fcf5fd1756e038e6c425ecac/src/schema-encoder.ts#L199). We'll include this information in the documentation as well.

I hope this answers your questions and provides you with the necessary resources to proceed. Please let me know if you have any further questions or need clarification. Thanks for your input!

**Comment by ccamrobertson** [comment]
@slavik0329 thanks -- re external provider, I suppose my question here was whether or not some pinning function would eventually be built into the SDK (via EASScan or a node of our choice).

That's extremely helpful, thanks. Looking forward to the documentation as I mainly want to make sure that everything is formatted correctly. Happy to close this (or leave open until the documentation is ready if helpful).
