### ISSUE TITLE
private data attestation insecure

### ISSUE THREAD

**Issue by sirpy** [ethereum-attestation-service/eas-sdk#33]
Where can I review the code for your private data attestations?

In the docs you outline how to create private data attestations.
If the data space size is low, the attestation can be easily guessed.
For example a schema of
Name, Gender, over100k, credit score

Assuming the verifier knows his customer name, he can easily iterate through the possible values and guess the merkle root as there are only
2(gender)*2(over100k)*1000 different options.

To make it resistant each data needs to be paired with a random nonce node. (can be made deterministic for example by using the hash of the signed value by the recipient private key)

**Comment by slavik0329** [comment]
Correct, that is what we do. Every leaf has its own random 256 bit salt. We will add the code for this into the sdk ASAP.

**Comment by sirpy** [comment]
@slavik0329 when will this be part of the sdk?
