### ISSUE TITLE
Possibly incorrect primary type

### ISSUE THREAD

**Issue by micwallace** [ethereum-attestation-service/eas-sdk#37]
Hey @slavik0329,

Should the primary type here be "Attest" instead of "Attestation"?

https://github.com/ethereum-attestation-service/eas-sdk/blob/b68b35f1bbb2c5ebdb35e6d0bdac967d682965d5/src/offchain/offchain.ts#L85

**Comment by lbeder** [comment]
Fixed in https://github.com/ethereum-attestation-service/eas-sdk/pull/38
