### ISSUE TITLE
Please add some examples for delegated attestation and delegated proxy attestation

### ISSUE THREAD

**Issue by shrekuu** [ethereum-attestation-service/eas-sdk#39]
Hi @slavik0329 , I see we only have on-chain/off-chain attestation examples.

Please add some examples about delegated on-chain attestation, as well as some delegated proxy on-chain attestation.

Thanks. ❤️

Currently I am using the code from the tests. I use `signDelegatedProxyAttestation` on server side, then use `attestByDelegationProxy` on the client side, to achieve this feature: ["you have a single entity like a KYC provider attesting to many users while wanting the users to pay for the gas"](https://docs.attest.sh/docs/tutorials/delegated-attestations#:~:text=you%20have%20a%20single%20entity%20like%20a%20KYC%20provider%20attesting%20to%20many%20users%20while%20wanting%20the%20users%20to%20pay%20for%20the%20gas) . I haven't get it work correctly.

**Comment by lbeder** [comment]
Do you still have this issue? Using `signDelegatedProxyAttestation` and `attestByDelegationProxy` is the right approach.
