### ISSUE TITLE
Include docs for generating offline link

### ISSUE THREAD

**Issue by carlbarrdahl** [ethereum-attestation-service/eas-sdk#41]
Hi!
I'm working on a project using EAS where I can to create offchain signatures and embed as QR codes to be verified. The QR code should point to the EAS scanner so I'm trying to figure out how to generate the attestation id used in the URL.

For example I want to create a URL like this:
https://easscan.org/offchain/url/#attestation=eNqlkDuOHDEMRO%2FSccPgR%2Fwo3J3xXMJwIIlkNHCw8AB7fGv6CmZIFF8V69cBP0iPE88Dvj%2BQwB78%2BTmI2k9affHSu4yH8h1yojjdUtyOt5h7I4Xl4eXpNoOIu8wRK21WrvTszRqADi4MHllNqLv0DgARF0R8%2BAhPnW5qSxtgbFgY4KCp0ky2XyKRKwDv044LHaYqNMZ5nORvDtRE1XWPB7LbTaZyPQaJEVLvdbcJ6sV1mU5qpUmVXZSwS5ZoTlumOkoaAYUNJpHc2TFqUK%2FFCBOxUBdfEBcBSAddhWnNWwvZmWFoeOdKzNDSCcY%2BBbJx2FaRBXiuofiG7NrVwb3tRk64Fn%2B%2FXnk99H%2Bz8XD%2BeT2fv%2F8BTKB3Mg%3D%3D

From my research I've found that the id is a gzipped base64 encoded string (with encodeURIComponent).

I have been able to successfully decode it into a valid javascript array with the following:
```ts
const pako = require("pako")

const id = decodeURIComponent("eNqlkDuO...")
// Create buffer from decoded base64
const buffer = Buffer.from(atob(id), "binary");

// Unzip using pako
const decompressed = pako.inflate(buffer, { to: "string" });
```

This gives the following array:
```js
[
    "0.26",
    1,                                                                    // version
    "0xA1207F3BBa224E2c9c3c6D5aF63D0eb1582Ce587",                         // verifying contract
    "0x394260c8d8f8e87bd22395badce7bfece8e9474006a3f1d3aef45298599000dd", // sig.r
    "0x58a8ad8e6b8767c6401de87d701a2b65475587e1228600399091c180b660431b", // sig.s
    28,                                                                   // sig.v
    "0x0fb166cDdF1387C5b63fFa25721299fD7b068f3f",                         // signer address
    "0xb24f6e2fe9562195ef56eb7c766af54202d7a3255e06a1dfa29fc310b11f16c3", // uid
    "0x85500e806cf1e74844d51a20a6d893fe1ed6f6b0738b50e43d774827d08eca61", // schema
    "0",                                                                  // ?
    1680884900,                                                           // message.time
    0,                                                                    // ?
    "0",                                                                  // ?
    true,                                                                 // message.revocable
    "0x0000000000000000000000000000000000000000000000000000000000000001", // message.data
    0,                                                                    // ?
    null                                                                  // ?
  ];
```

I should then be able to compress it into the original ID:

```ts
const compressed = pako.deflate(JSON.stringify(decompressed), { to: "string" });
encodeURIComponent(Buffer.from(compressed).toString("base64"));
```
I haven't been able to get the same ID as in the URL. This one starts with:
`eJylkTlOA0AMRe%...t8AP0qn6m`

Here's the code:
https://replit.com/@CarlBarrdahl/PakoTest#index.js

Questions:
- How to properly encode the compressed data?
- What are the variables in the array marked with ?

Grateful for any help!

**Comment by slavik0329** [comment]
Excellent reverse engineering. You almost got there in your own. We will add this functionality to the SDK asap, but I'll send you a gist you can use for now. I'll be able to send it in a few hours.

**Comment by slavik0329** [comment]
@carlbarrdahl Actually was able to do it quicker than expected. Here you go: https://gist.github.com/slavik0329/b5b1d9cc156fce6c51a0256165be674d

Let me know if this works so I can close this issue.

**Comment by carlbarrdahl** [comment]
> @carlbarrdahl Actually was able to do it quicker than expected. Here you go: https://gist.github.com/slavik0329/b5b1d9cc156fce6c51a0256165be674d
> 
> Let me know if this works so I can close this issue.

Beautiful! Thank you so much for putting together this and the quick reply.

If works to encode it but when I run it through `decodeBase64ZippedBase64` I get this error:
```
inflate.js:384 Uncaught incorrect header check
```
And the URL return `Signature check failed`
https://easscan.org/offchain/url/#attestation=eNqlkE1uXEEIhO%2Fy1k8R%2F9Bbj51LWF5AN32AKJFy%2FPSMjxB2lOCjqM8LfpBftxDcF%2FzFVFNY0LNmsoy1Qip3hvqA5rah2hVyPYdhCG%2BktsQcABaszRLa0iTiWjIgLQNbiLvqINHOxG7f1CtfEJoRsSArnSYqEsYeRb4m%2BzHVwX584CIVecqgchpwOAvBtK%2Bb%2FMmJfHuchRyPN2PkD3B8vINu%2FWmHALjfx%2BMD13od1cFEsmbz8GJv9NqNyxOoWcEE01sZ%2FXiPtAbumCEGE20jxrdz3JXVECtOVrwEgGqYWvTkucbsoNF8Xt1V3bARtBykiklU9Am5brQIEDcTAbzhpf3%2B9adfAf9f4XV4%2BPUPhQB31w%3D%3D

<details>
<summary>Attestation data</summary>

```ts
{
    "domain": {
        "name": "EAS Attestation",
        "version": "0.27",
        "chainId": 420,
        "verifyingContract": "0x1a5650d0ecbca349dd84bafa85790e3e6955eb84"
    },
    "primaryType": "Attest",
    "message": {
        "version": 1,
        "recipient": "0x0000000000000000000000000000000000000000",
        "expirationTime": 0,
        "time": 1688047664401,
        "revocable": true,
        "nonce": 0,
        "schema": "0x21fbabe08d8ca33d4002b96568ec3cd9ce829e3f2efbbee0f105b704bb324545",
        "refUID": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "data": "0x0000000000000000000000000000000000000000000000000000000000000001"
    },
    "types": {
        "Attest": [
            {
                "name": "version",
                "type": "uint16"
            },
            {
                "name": "schema",
                "type": "bytes32"
            },
            {
                "name": "recipient",
                "type": "address"
            },
            {
                "name": "time",
                "type": "uint64"
            },
            {
                "name": "expirationTime",
                "type": "uint64"
            },
            {
                "name": "revocable",
                "type": "bool"
            },
            {
                "name": "refUID",
                "type": "bytes32"
            },
            {
                "name": "data",
                "type": "bytes"
            }
        ]
    },
    "signature": {
        "v": 27,
        "r": "0x0943f12e6a1a9006835e3485e4e24475b490a6a81e423ebbbca16e34fe7f2eda",
        "s": "0x2c888d0aba72c151218f9b27dc37420e8373491d2544b27d0541d2070ba7832f"
    },
    "uid": "0x593224dce397b37e17bfe1d7a02e350641a7e531781e8a6e03e8c8460c16f118"
}
```
</details>

**Comment by slavik0329** [comment]
@carlbarrdahl It looks like this is because the chainID of the offchain attestation is 420, but you are using mainnet chainID. When you switch URL to optimism-goerli (420) it works: https://optimism-goerli.easscan.org/offchain/url/#attestation=eNqlkE1uXEEIhO%2Fy1k8R%2F9Bbj51LWF5AN32AKJFy%2FPSMjxB2lOCjqM8LfpBftxDcF%2FzFVFNY0LNmsoy1Qip3hvqA5rah2hVyPYdhCG%2BktsQcABaszRLa0iTiWjIgLQNbiLvqINHOxG7f1CtfEJoRsSArnSYqEsYeRb4m%2BzHVwX584CIVecqgchpwOAvBtK%2Bb%2FMmJfHuchRyPN2PkD3B8vINu%2FWmHALjfx%2BMD13od1cFEsmbz8GJv9NqNyxOoWcEE01sZ%2FXiPtAbumCEGE20jxrdz3JXVECtOVrwEgGqYWvTkucbsoNF8Xt1V3bARtBykiklU9Am5brQIEDcTAbzhpf3%2B9adfAf9f4XV4%2BPUPhQB31w%3D%3D

**Comment by slavik0329** [comment]
@carlbarrdahl As far as the pako error, make sure you are only sending in the base64 string and not the whole url. You may have to decodeURIComponent() on the string if its url encoded before sending it to decode function.

**Comment by slavik0329** [comment]
The functionality has been added to the SDK in https://github.com/ethereum-attestation-service/eas-sdk/pull/43
