### ISSUE TITLE
How to publish off-chain attestation by EAS-SDK?

### ISSUE THREAD

**Issue by crazyyuan** [ethereum-attestation-service/eas-sdk#51]
We are ready to make off-chain attestation and publish it to query after.
But the SDK is just for making, how to publish it by EAS-SDK, and then display on the EAS platform.

Or some other suggestions for me.

**Comment by slavik0329** [comment]
@crazyyuan please check out the "submitSignedAttestation" function here: https://github.com/ethereum-attestation-service/met-irl/blob/offchain/src/utils/utils.ts

**Comment by crazyyuan** [comment]
> @crazyyuan please check out the "submitSignedAttestation" function here: https://github.com/ethereum-attestation-service/met-irl/blob/offchain/src/utils/utils.ts

Great helpful, thanks!

**Comment by evan976** [comment]
This request address(`https://easscan.org/offchain/store`) reports an error: `500 Unexpected Server Error`. What is the reason? Thank you
