### ISSUE TITLE
Error: getOffchain tips 'this.contract.getAddress is not a function'

### ISSUE THREAD

**Issue by crazyyuan** [ethereum-attestation-service/eas-sdk#55]
After I created EAS instance.
Test getAttestation feature is normal.
But when I try to getOffchain, some error comes.
I printed the EAS  instance, the contract has no getAddress function.

version
"@ethereum-attestation-service/eas-sdk":"^1.1.0-beta.3"

![image](https://github.com/ethereum-attestation-service/eas-sdk/assets/1342404/ed501701-9036-4f12-bbaa-1f7fb8b529ce)
![image](https://github.com/ethereum-attestation-service/eas-sdk/assets/1342404/9ba9476f-78c4-4d57-bfd6-aeb67ee5e946)

**Comment by lbeder** [comment]
`this.contract.getAddress` is usually a result of using ethers v5. I'll move ethers v6 as a production dependency to reduce the cases when it happens

**Comment by lbeder** [comment]
Oh, it's already a production dependency, so something else might have been overriding it

**Comment by crazyyuan** [comment]
> @crazyyuan Can you please share the chain you're using and also if possible can you share your code repo so we can investigate?

https://github.com/lxdao-official/fairsharing-frontend/blob/develop/src/app/project/%5Bid%5D/contribution/page.tsx
line: 35

![image](https://github.com/ethereum-attestation-service/eas-sdk/assets/1342404/f6469b94-890d-440b-ada8-114c76a99473)
click 'Test Prepare contribution' button will reproduce it.

**Comment by lbeder** [comment]
If you want to use SDK >1.0.0 then you have to use ethers v6

**Comment by crazyyuan** [comment]
> If you want to use SDK >1.0.0 then you have to use ethers v6

thanks! I solved it with your suggestion.
