### ISSUE TITLE
Is it possible to revoke off-chain attestation but didn't through the EAS contract?

### ISSUE THREAD

**Issue by crazyyuan** [ethereum-attestation-service/eas-sdk#56]
I don't know, why removing off-chain attestation needs to interact with the EAS contract.
Writing to contract will cost gas. it's unfriendly to off-chain operations.

**Comment by lbeder** [comment]
Offchain attestations are, as their name suggests, are fully off-chain, so they aren't optimized to be used onchain. One convention to revoke offchain attestation is by calling the `revokeOffchain` onchain method with their UID.

I'd recommend taking these questions to our Telegram or Discord dev groups, which you can find here: https://attest.sh/

**Comment by slavik0329** [comment]
> I don't know, why revoking off-chain attestation needs to interact with the EAS contract.
> 
> Writing to contract will cost gas. it's unfriendly to off-chain operations.

You can come up with your own scheme if you want to revoke fully offchain, however there would be no way for anyone to know whether an attestation was revoked unless they also had in their possession the revocation. This is why it makes sense. Revoking offchain only publishes a single bytes32 hash. Along with merkle trees it can be extremely cheap to revoke and maintain attestation safety.
