### ISSUE TITLE
Offchain Attestation Gives Error

### ISSUE THREAD

**Issue by t9fiction** [ethereum-attestation-service/eas-sdk#60]
so what happens is that,
as soon as the application reaches at the line 
 
 `const offchain = await eas.getOffchain();`
 
 It gives the following error
Uncaught (in promise) TypeError: this.contract.getAddress is not a function

I am not using typescript, just simple javascript with react.

**Comment by lbeder** [comment]
It usually happens if you are using ethers v5, which is no longer supported by the latest versions of the SDK, which were upgraded to ethers v6.
