### ISSUE TITLE
When sdk for private data proofs

### ISSUE THREAD

**Issue by sirpy** [ethereum-attestation-service/eas-sdk#64]
- sdk for creating private data attestations using merkle trees
- sdk for creating proofs
- smart contract code for validating proofs

**Comment by sirpy** [comment]
?

**Comment by sudoFerraz** [comment]
This would be great! +1

**Comment by lbeder** [comment]
Almost there! https://github.com/ethereum-attestation-service/eas-sdk/pull/103
