### ISSUE TITLE
Something error occurs when signing data with the mobile Metamask wallet

### ISSUE THREAD

**Issue by crazyyuan** [ethereum-attestation-service/eas-sdk#74]
Our application integrates with the eas-sdk and works on PC browsers.
But when signing data off-chain with the mobile Metamask wallet, the error occurs. After some debugs, I couldn't locate the problem.
version: 1.1.0-beta.3
snapshot:
<img width="1427" alt="image" src="https://github.com/ethereum-attestation-service/eas-sdk/assets/1342404/90032481-ad35-4035-84ac-6517b959a1df">

**Comment by slavik0329** [comment]
@crazyyuan are you using rainbowkit/connectkit? If so this could be related to a wagmi bug which causes this error when you only enable a single chain. Try enabling multiple chains in the config.

**Comment by crazyyuan** [comment]
> @crazyyuan are you using rainbowkit/connectkit? If so this could be related to a wagmi bug which causes this error when you only enable a single chain. Try enabling multiple chains in the config.

Pretty thanks, it works when multiple chains are enabled.
