### ISSUE TITLE
Version2 not defined

### ISSUE THREAD

**Issue by monique-baumann** [ethereum-attestation-service/eas-sdk#79]
![Screenshot from 2024-01-16 15-29-07](https://github.com/ethereum-attestation-service/eas-sdk/assets/145258627/99e8cb4a-be62-45c6-9194-3fbb0405e36e)

https://github.com/ethereum-attestation-service/eas-sdk/blob/master/README.md?plain=1#L300

**Comment by monique-baumann** [comment]
additionally you might check and simplify bigint vs. number typing. This seems not too consistent yet - e.g. in the context of https://github.com/ethereum-attestation-service/eas-sdk/blob/master/README.md?plain=1#L317

**Comment by lbeder** [comment]
We can't maintain external builds/framework ourselves

**Comment by lbeder** [comment]
> additionally you might check and simplify bigint vs. number typing. This seems not too consistent yet - e.g. in the context of https://github.com/ethereum-attestation-service/eas-sdk/blob/master/README.md?plain=1#L317

`chainId` is should be `BigInt` everywhere. It appears that your own managed types aren't up-to-date.

**Comment by lbeder** [comment]
@monique-baumann please try deleting `dist` and running `pnpm build` or checkout a clean version.
