### ISSUE TITLE
Offchain attestation that requires refUID

### ISSUE THREAD

**Issue by thongxuan** [ethereum-attestation-service/eas-sdk#91]
Hi, I'm in a situation where I have to create off-chain attestation that references an on-chain attestation.

Also, my schema resolver logic requires validating the attestation provided in refUID.

Due to the fix in this PR: https://github.com/ethereum-attestation-service/eas-sdk/pull/54, which set the refUID to be zero bytes 32 all the time, my resolver logic fails.

https://github.com/ethereum-attestation-service/eas-sdk/blob/ef088c138a1d72d7a673cb73d89c9c3b431be2ec/src/offchain/offchain.ts#L217-L220

My question: could we allow simulating resolver with `refUID: params.refUID || ZERO_BYTES32` ?

**Comment by lbeder** [comment]
Great suggestion @thongxuan! We will finish working on some important fixes and release this fix with the new version asap.

**Comment by thongxuan** [comment]
Great to hear that! Thank you!!
