### ISSUE TITLE
Import PartialTypedDataConfig is failing

### ISSUE THREAD

**Issue by zeGzD** [ethereum-attestation-service/eas-sdk#95]
Hi,

I am currently trying to verify an offchain attestation by following the provided example from the readme.
Unfortunately the code snippet seems irrelevant (or am I missing something?).

Thank you for the clarification/fix.

_Edit_: the [same example from the documentation](https://docs.attest.sh/docs/developer-tools/eas-sdk#verify-an-offchain-attestation) seems to exhibit even more issues.

**Comment by lbeder** [comment]
Hi @zeGzD, 
We need to update the documentation to support the newer version. We'll do it soon 🙏

**Comment by lbeder** [comment]
Resolved
